### ISSUE TITLE
wizCanvas.load() issues android

### ISSUE THREAD

**Issue by DamianS1987** [Wizcorp/phonegap-plugin-wizCanvas#13] opened 2014-03-05 01:12 UTC
Hi,
I'm trying to load a file on the already created wizCanvas but nothing seems to happen as soon as I do so. I receive neither success nor fail callback. I installed the example given on samsung S4 (android 4.3) and Nexus 7 (android 4.4.2) but it doesn't seem to work either. It's the only method that doesn't work for me.  I understand that it was suppose to increase the number of curves to 140.
loadme.js:
var maxCurves = 140;

Please, can you let me know how to use it? Do you have any other working examples?

Thank you in advance,
Damian

**Comment by bassemBMI** [comment] 2016-02-20 18:44
Hi,
I have the same problem with iOS 8.1.1, I installed the plugin and build it successfully but I have errors when calling create or load function:

console.log(wizCanvas);
==> {name: "mainView", views: Object, throwError: function, create: function, remove: function, ...}

wizCanvas.create('mainView',{}, function(success){console.log('success',success);}, function(fail){console.log('fail', fail);});
==> fail - null

wizCanvas.show('mainView',{}, function(success){console.log('success',success);}, function(fail){console.log('fail', fail);});
==> TypeError: undefined is not an object (evaluating 'this.views[name].show')

Same error for wizCanvas.load();
==> TypeError: undefined is not an object (evaluating 'this.views[name].load')

Do I missed something in the configuration ?

**Comment by jrouault** [comment] 2016-02-22 02:33
Hello,

Sorry but could you create an appropriate issue for your problem? When you do so, could you provide an example so that we can reproduce it?

I will close this issue because it should have been solved by #43.

**Closed by jrouault** 2016-02-22 02:33 UTC
